pay-flow:
  runner:
    create-exp: 'T(java.util.concurrent.Executors).newFixedThreadPool(2)'
  node-handlers:
    - create-exp: 'new com.aihuishou.payflow.handler.impl.DefaultNodeHandler()'
  flow-handlers:
    - create-exp: 'new com.aihuishou.payflow.handler.impl.DefaultFlowHandler()'
  flows:
    - id: 'flow1'
      nodes:
        - id: 'a1'
          start: true
          create-exp: 'new com.aihuishou.payflow.action.impl.A1NodeActionImpl()'
          conditions:
            - when-nodes:
                - create-exp: 'new com.aihuishou.payflow.action.impl.ToA2ConditionAction()'
              to-nodes:
                - 'a2'
            - when-nodes:
                #需要支持多种判断，简单的 el 和 ConditionAction
                - create-exp: 'new com.aihuishou.payflow.action.impl.ToA3ConditionAction()'
                - simple-exp: 'actionResult == "a1 to a3"'
              to-nodes:
                - 'a3'
        - id: 'a2'
          create-exp: 'new com.aihuishou.payflow.action.impl.A2NodeActionImpl()'
          end: false
          conditions:
            - when-nodes:
                - create-exp: 'new com.aihuishou.payflow.action.impl.ToA6ConditionAction()'
              to-nodes:
                - 'a2'
            - when-nodes:
                - create-exp: 'new com.aihuishou.payflow.action.impl.ToA6ConditionAction()'
                  is-negated: true
              to-nodes:
                - 'a6'
        - id: 'a3'
          create-exp: 'new com.aihuishou.payflow.action.impl.A3NodeActionImpl()'
          delay-level: 1
          conditions:
            - when-nodes:
                - create-exp: 'new com.aihuishou.payflow.action.impl.ToA4A5ConditionAction()'
              to-nodes:
                - 'a4'
                - 'a5'
        - id: 'a4'
          create-exp: 'new com.aihuishou.payflow.action.impl.A4NodeActionImpl()'
          end: true
        - id: 'a5'
          create-exp: 'new com.aihuishou.payflow.action.impl.A5NodeActionImpl()'
          end: true
        - id: 'a6'
          create-exp: 'new com.aihuishou.payflow.action.impl.A6NodeActionImpl()'
          retry-times: 10
          retry-algorithm-exp: "new com.aihuishou.payflow.algorithm.impl.ExponentialBackoffRetryAlgorithm(5)"
          end: true